# Generated by Django 3.0.2 on 2020-02-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref_process_type',
        ),
    ]
