# Generated by Django 3.0.2 on 2020-02-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ref_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='process_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Ref_process_type'),
            preserve_default=False,
        ),
    ]
