# Generated by Django 3.0.2 on 2020-02-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agreement_process_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='main_phone',
        ),
    ]
