# Generated by Django 3.0.2 on 2020-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customer_main_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='main_phone',
            field=models.IntegerField(null=True),
        ),
    ]
