# Generated by Django 3.0.2 on 2020-02-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_main_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_csi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('phone2', models.CharField(max_length=12, null=True)),
                ('addr', models.CharField(max_length=255, null=True)),
                ('index', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ref_region')),
            ],
        ),
        migrations.RemoveField(
            model_name='ispol_sheet',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='ispol_sheet',
            name='nadpis',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='fio_csi',
            new_name='nadpis_doc_no',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='phone_csi',
        ),
        migrations.AddField(
            model_name='agreement',
            name='ispol_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='ispol_doc_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='nadpis_initial_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='nadpis_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Ispol_nadpis',
        ),
        migrations.DeleteModel(
            name='Ispol_sheet',
        ),
        migrations.AddField(
            model_name='agreement',
            name='csi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ref_csi'),
        ),
    ]
