# Generated by Django 3.0.2 on 2020-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contact_ref_contact_result_ref_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
