# Generated by Django 3.0.2 on 2020-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contact_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='installment_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='installment_dt_to',
            field=models.DateField(null=True),
        ),
    ]
