# Generated by Django 3.0.2 on 2020-02-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200218_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='created',
            field=models.DateField(),
        ),
    ]
