# Generated by Django 3.0.4 on 2020-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200424_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='give_csi_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recall_csi_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='return_ispol_doc_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stop_actions_csi_dt',
            field=models.DateField(null=True),
        ),
    ]
