# Generated by Django 3.0.4 on 2020-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200424_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='court_costs',
            field=models.FloatField(default=0),
        ),
    ]
