# Generated by Django 3.0.4 on 2020-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_agreement_court_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='court_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='main_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
