# Generated by Django 3.0.4 on 2020-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200430_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='commission_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='commission_start',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='court_costs_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='court_costs_start',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='main_debt_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='main_debt_start',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='penalty_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='penalty_start',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='percent_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='percent_start',
        ),
    ]
