# Generated by Django 3.0.4 on 2020-04-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200430_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_court_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_main_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='end_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_court_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_main_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_percent',
            field=models.FloatField(default=0),
        ),
    ]
