# Generated by Django 3.0.4 on 2020-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200504_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='main_debt',
            new_name='current_commission',
        ),
        migrations.AddField(
            model_name='agreement',
            name='current_court_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='current_main_debt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='current_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='current_percent',
            field=models.FloatField(default=0),
        ),
    ]
