# Generated by Django 3.0.7 on 2020-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_agreement_main_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='load_dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
