# Generated by Django 3.0.7 on 2020-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_payment_load_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='current_penalty_agreement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='penalty_agreement',
            field=models.FloatField(default=0),
        ),
    ]
