# Generated by Django 3.0.7 on 2020-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200709_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_penalty_agreement',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_penalty_agreement',
            field=models.FloatField(null=True),
        ),
    ]
