# Generated by Django 3.0.7 on 2020-08-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_contragent_type_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='contragent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Contragent'),
            preserve_default=False,
        ),
    ]
