# Generated by Django 3.0.7 on 2020-08-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_agreement_contragent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='contragent',
        ),
    ]
