# Generated by Django 3.0.7 on 2020-08-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_agreement_contragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='contragent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_agreement_contragent_id', to='api.Contragent'),
        ),
    ]
