# Generated by Django 3.0.7 on 2020-11-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200819_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csi_actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_of_salary', models.CharField(default='N', max_length=1)),
                ('arrest_of_property', models.CharField(default='N', max_length=1)),
                ('arrest_of_accounts', models.CharField(default='N', max_length=1)),
                ('arrest_of_deparure', models.CharField(default='N', max_length=1)),
                ('give_csi_dt', models.DateField(null=True)),
                ('recall_csi_dt', models.DateField(null=True)),
                ('stop_actions_csi_dt', models.DateField(null=True)),
                ('return_ispol_doc_dt', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agreement')),
                ('csi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ref_csi')),
            ],
        ),
    ]
