# Generated by Django 3.0.7 on 2020-12-02 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_csi_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='csi_actions',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
